services:
  kasse:
    build: ./kasse
    ports:
      - "8080:8080"
  ticket:
    build: ./ticket-pwa
    ports:
      - "8081:8080"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  redis-init:
    build: ./redis
    depends_on:
      - redis
  server:
    build: ./server
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - redis-init