services:
  kasse:
    build: ./kasse
    ports:
      - "${PORTBASE}80:8080"
  ticket:
    build: ./ticket-pwa
    ports:
      - "${PORTBASE}81:8080"

  redis:
    image: "redis:alpine"
    ports:
      - "${PORTBASE}79:6379"
  redis-init:
    build: ./redis
    depends_on:
      - redis
  server:
    build: ./server
    ports:
      - "${PORTBASE}50:8000"
    depends_on:
      - redis
      - redis-init